### ISSUE TITLE
secret key is exposed

### ISSUE THREAD

**Issue by hutchic** [puskomedia/whois#5]
recaptcha secret key needs to be kept secret and as such shouldn't be committed to git

https://github.com/puskomedia/whois/blob/master/whois.php#L49

https://developers.google.com/recaptcha/intro

> The secret key authorizes communication between your application backend and the reCAPTCHA server to verify the user's response. The secret key needs to be kept safe for security purposes.

**Comment by samsulmaarif** [comment]
Thanks @hutchic i was'n aware of this.
